---
- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Extract the artifact"
  become: yes
  ansible.builtin.unarchive:
    src: roles/deploy/tasks/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Executing node"
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
    npm run migrations
    pm2 delete all
    export $(grep TYPEORM_HOST /home/ubuntu/backend/.env) && pm2 start npm -- start

- name: check pm2 log
  become: yes
  shell: pm2 logs --nostream
  register: pm2Log

- name: Show PM2 log
  debug:
    var: pm2Log
    verbosity: 2
