---
- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Extract the artifact"
  become: yes
  ansible.builtin.unarchive:
    src: roles/deploy/tasks/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Executing node"
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
    npm run migrations
    pm2 stop default
    export $(grep TYPEORM_HOST /home/ubuntu/backend/.env)
    pm2 start npm -- start
    pm2 ls
